extends GDScript
## Setup:[br]
	## As of current, modchart scripts must be put in specific folders, those being...[br]
	## res://assets/scripts/global - for scripts that run in any song[br]
	## res://assets/scripts/songs/current_song_folder - for scripts that run in a specific song[br]
	## all scripts present in those folders will be ran when initialising gameplay.[br][br]
## Callbacks:[br]
	## NOTE: all callbacks that return int can return values to stop the original functions[br]
	## possible ints that can be returned are...[br]
	## 0 - Does nothing and continues the original function, this is default if the function type isn't int.[br]
	## ALIAS: ModchartPack.CallableRequest.NONE
	## 1 - Stops the original function[br]
	## ALIAS: ModchartPack.CallableRequest.STOP
	## int(-2^15-1) - Stops this script[br]
	## ALIAS: ModchartPack.CallableRequest.END
##[br][br]
## _on_ready(scene: Node) -> void[br]
## _set_hud(scene: Node) -> int[br]
## _on_hud_loaded(scene: Node, hud_name: StringName) -> void[br]
## _on_hud_unloaded(scene: Node, hud_name: StringName) -> void[br]
#### - just in case you wanna modify the hud before the game loads the default one yk[br]
## _on_countdown(scene: node, beat: int) -> int[br]
## _on_process(scene: Node, delta: float) -> int[br]
## _post_process(scene: Node, delta: float) -> void[br]
## _on_ibeat_reached(scene: node, beat: int) -> int[br]
## _on_istep_reached(scene: node, step: int) -> int[br]
## _on_ibar_reached(scene: node, bar: int) -> int[br]
## _on_unhandled_input(scene: Node, event: InputEvent) -> void[br]
## _on_pause(scene: Node) -> int[br]
## _on_exit_tree(scene: Node) -> int[br]
